import {
  IPublicKeyOnlyWallet,
  IFullWallet,
  IEtherWalletLocked,
  IEtherWalletUnlocked
} from './';
/**
 * @description import a brain wallet used by Ether.Camp
 * @param input
 * @param password
 */
export function fromEtherCamp(passphrase: string): IFullWallet;

/**
 * @description import a wallet generated by EtherWallet
 * @param input
 * @param password
 */
export function fromEtherWallet(
  input: IEtherWalletLocked | IEtherWalletUnlocked | string,
  password: string
): IFullWallet;

/**
 * @description  import a wallet from a KryptoKit seed
 * @param entropy
 * @param seed
 */
export function fromKryptoKit(entropy: string, seed: string): IFullWallet;

/**
 * @description import a brain wallet used by Quorum Wallet
 * @param passphrase
 * @param userid
 */
export function fromQuorumWallet(
  passphrase: string,
  userid: string
): IFullWallet;
